FROM node:8.11.2-alpine

# Create app directory

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies

COPY package*.json /usr/src/app
RUN npm install

RUN npm install -g pm2

COPY . /usr/src/app

EXPOSE 1337

CMD [ "pm2", "start", "app.js" ]

